### ISSUE TITLE
The reverse view should group all the packages that require a certain package together.

### ISSUE THREAD

**Issue by eli-b** [naiquevin/pipdeptree#49] opened 2016-07-06 13:21 UTC
When using `pipdeptree -l -r`, it's confusing to see the same package listed multiple times in the (long) list of required packages. It can lead a user to incorrectly think a package is only required by one package, because they didn't notice the package is listed again elsewhere in the output.

Also, the same dependency is sometimes listed more than once. For example, I get:
> six==1.10.0
  - protobuf==3.0.0b2.post2 [requires: six>=1.1.0]
    - gcloud==0.12.0 [requires: protobuf]
six==1.10.0
  - protobuf==3.0.0b2.post2 [requires: six]
    - gcloud==0.12.0 [requires: protobuf]

And sometimes I also get seeming contradictory dependency listings (yes, I did use -r -l here too):
> six==1.10.0
  - Paste==2.0.3 [requires: six>=1.3.0]
    - pysaml2==4.0.5 [requires: Paste]
six==1.10.0
  - Paste==2.0.3 [requires: six>=1.5]
    - pysaml2==4.0.5 [requires: Paste]

**Comment by naiquevin** [comment] 2016-07-06 17:24
Duplicate of #45. I haven't had the time to look into this :-(. Will try to find some time this month. Feel free to submit pull requests.

**Comment by eli-b** [comment] 2016-07-06 19:44
My point here was mostly about the need to group requiring packages in the
same place to avoid confusion.
The curious examples I gave were an aside. I should have been clearer about
the main subject.

בתאריך יום ד׳, 6 ביולי 2016, 20:24, מאת Vineet Naik ‏<
notifications@github.com>:

**Comment by naiquevin** [comment] 2016-08-21 06:03
Fix included in the 0.7.0 release on PyPI.

**Closed by naiquevin** 2016-08-21 06:03 UTC
