### ISSUE TITLE
pipdeptree -f is broken

### ISSUE THREAD

**Issue by geoffreybrown** [naiquevin/pipdeptree#114] opened 2019-02-27 10:03 UTC
Traceback (most recent call last):
  File "/usr/local/bin/pipdeptree", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pipdeptree.py", line 623, in main
    frozen=args.freeze, exclude=exclude)
  File "/usr/local/lib/python3.5/dist-packages/pipdeptree.py", line 331, in render_tree
    lines = flatten([aux(p) for p in nodes])
  File "/usr/local/lib/python3.5/dist-packages/pipdeptree.py", line 331, in <listcomp>
    lines = flatten([aux(p) for p in nodes])
  File "/usr/local/lib/python3.5/dist-packages/pipdeptree.py", line 319, in aux
    node_str = node.render(parent, frozen)
  File "/usr/local/lib/python3.5/dist-packages/pipdeptree.py", line 153, in render
    return self.render_as_root(frozen)
  File "/usr/local/lib/python3.5/dist-packages/pipdeptree.py", line 187, in render_as_root
    return self.__class__.frozen_repr(self._obj)
  File "/usr/local/lib/python3.5/dist-packages/pipdeptree.py", line 159, in frozen_repr
    fr = FrozenRequirement.from_dist(obj, [])
TypeError: from_dist() takes 2 positional arguments but 3 were given

**Comment by naiquevin** [comment] 2019-02-28 06:03
This issue was fixed in the last release ie 0.13.2. Please upgrade to the latest version on pypi. 

Duplicate of #113

**Closed** 2019-07-13 05:16 UTC
